assembly-versioning-scheme: MajorMinorPatch 
next-version: 1.2.0-rc3
branches:
  features[/-]:
    mode: ContinuousDeployment
    tag: useBranchName
    increment: Inherit
    prevent-increment-of-merged-branch-version: false
    track-merge-target: false
  dev:
    mode: ContinuousDeployment
    tag: dev
    increment: Minor
    prevent-increment-of-merged-branch-version: false
    track-merge-target: true
